#!/bin/ksh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
export PATH=../../../proto/root_$(uname -p)/usr/bin:$PATH
export PYTHONPATH=../../../proto/root_$(uname -p)/usr/lib/python2.4/vendor-packages
export PACKAGEPATH=../../../packages/i386

#
# This needs to be kept in sync with the redistributable version number.
#
REDIST_CLUSTER_VERSION=0.1

buildid=$(echo $1 | tr -d '[a-z]')

# These are both hacky, horrible ways to get this information, but until there
# is a client API in place that can handle all repository types, it's necessary.
if [[ "$REPO" == http* ]]; then
        # create a temp image so we can get things from the repo
        pkg image-create -a opensolaris.org=$REPO ./temp_image
        pkg -R ./temp_image contents -o action.raw -H -t depend -r \
                redistributable@$REDIST_CLUSTER_VERSION-0.${buildid} | \
                sed 's/type=require/type=incorporate/'
        rm -r ./temp_image
elif [[ "$REPO" == file* ]]; then
        REPO_PATH=$(echo $REPO | sed 's|file://||')
        MPATH=$REPO_PATH/pkg/redistributable
        MANIFEST=$(ls $MPATH/${REDIST_CLUSTER_VERSION}%2C*-0.${buildid}* | \
            sort -r | head -1)
        cat $MANIFEST | grep '^depend' | sed 's/type=require/type=incorporate/'
else
        exit 1
fi

echo 'set name=description value="entire incorporation"'
