#!/bin/bash -e
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
MACH=$(uname -p)
export PATH=../../../proto/root_$MACH/usr/bin:$PATH
export PYTHONPATH=../../../proto/root_$MACH/usr/lib/python2.4/vendor-packages

buildid=$(echo $1 | tr -d '[a-z]')
pkgname=$2

PKG_ARCHIVE=../../../packages/$MACH
CHERRYPY_VER=$(pkgparam -d $PKG_ARCHIVE SUNWpython-cherrypy VERSION)
PYOPENSSL_VER=$(pkgparam -d $PKG_ARCHIVE SUNWpython-pyopenssl VERSION)

if [[ $pkgname == "SUNWpython-cherrypy" ]]; then
	pkgvers=$CHERRYPY_VER
elif [[ $pkgname == "SUNWpython-pyopenssl" ]]; then 
	pkgvers=$PYOPENSSL_VER
else
	pkgvers=0.5.11
fi

pkgdir=$PKG_ARCHIVE/$pkgname
pkgfmri="$pkgname@$pkgvers,5.11-0.$buildid"

eval `pkgsend open $pkgfmri`

# SUNWipkg-gui-l10n is empty, because SUNWipkg-gui contains the .mo files,
# but needs to exist, since it existed in build 95 and an early copy of
# build 96 with data in it.
if [[ $pkgname != "SUNWipkg-gui-l10n" ]]; then
	pkgsend import -T \*.py $pkgdir
fi

# We don't add a dependency on SUNWopenssl for SUNWpython-pyopenssl, since
# SUNWopenssl is always installed
if [[ $pkgname == "SUNWipkg" ]]; then
	pkgsend add depend fmri=SUNWpython-pyopenssl@$PYOPENSSL_VER-0.$buildid type=require
	pkgsend add depend fmri=SUNWpython-cherrypy@$CHERRYPY_VER type=require
elif [[ $pkgname == "SUNWipkg-gui" ]]; then
	pkgsend import $PKG_ARCHIVE/SUNWipkg-gui-data
	pkgsend import $PKG_ARCHIVE/SUNWipkg-gui-l10n
	pkgsend add depend fmri=SUNWipkg-gui-l10n type=require
fi
pkgsend close
