#!/bin/ksh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright (c) 2008, 2013 Oracle and/or its affiliates.  All rights reserved.
#
# An SMF method script for
# svc:/application/pkg/update:default
# It's sole purpose is to add or remove a crontab entry

. /lib/svc/share/smf_include.sh
. /lib/svc/share/pkg5_include.sh

REFRESH_PROG="/usr/lib/update-manager/update-refresh.sh"
SCHEDULE='30 0,9,12,18,21 * * *'

case $SMF_METHOD in
"start")
	add_cronjob $SMF_FMRI "$SCHEDULE" $REFRESH_PROG
	check_failure $? "unable to schedule pkg refreshes" $SMF_FMRI \
	    exit
	;;
"stop")
	remove_cronjob $SMF_FMRI $REFRESH_PROG
	check_failure $? "unable to unschedule pkg refreshes" $SMF_FMRI\
	    exit
	;;
*)
	echo "Command line invocation of ${0} unsupported."
	echo "This script is intended for smf(5) invocation only"
	exit $SMF_EXIT_ERR_NOSMF
	;;
esac
exit $SMF_EXIT_OK
