#!/usr/bin/ksh -p
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright (c) 2013, 2025, Oracle and/or its affiliates.
#

# Load SMF constants and functions
. /lib/svc/share/smf_include.sh
. /lib/svc/share/fs_include.sh
. /lib/svc/share/pkg5_include.sh

CHOWN=/usr/bin/chown
ZFS=/usr/sbin/zfs

case "$1" in
'start')
	vs_pkg_path=/var/share/pkg/repositories

	# check if we already have a mounted /var/share/pkg/repositories.
	# $fstype set by readmnttab() in /lib/svc/share/fs_include.sh
	readmnttab $vs_pkg_path < /etc/mnttab
	if [ "$fstype" = zfs ]; then
		exit $SMF_EXIT_OK
	fi

	readmnttab / < /etc/mnttab
	if [ "$fstype" != zfs ]; then
		# we're on a LiveCD, so exit immediately.
		exit $SMF_EXIT_OK
	fi

	# $special set by readmnttab()
	rpool=${special%%/*}
	vs_pkg=$rpool/VARSHARE/pkg
	vs_pkg_repo=$vs_pkg/repositories

	# If the 'repositories' dataset exists, we mount it along with any child
	# datasets, then exit.
	if $ZFS list $vs_pkg_repo >/dev/null 2>&1; then
		# Must mount the parent explicitly due to the canmount property
		# set to "noauto".
		$ZFS mount $vs_pkg
		check_failure $? "Unable to mount $vs_pkg" $SMF_FMRI exit

		child_fs_mount=0
		for child in $($ZFS list -H -r -t filesystem \
		    -o name $vs_pkg_repo); do
			$ZFS mount "$child"
			child_fs_mount=$((child_fs_mount + $?))
		done
		[ $child_fs_mount -eq 0 ]
		check_failure $? \
		    "Unable to mount child datasets of $vs_pkg_repo" \
		    $SMF_FMRI exit
		exit $SMF_EXIT_OK
	fi

	# Otherwise, we need to create the datasets, taking care to set
	# canmount=noauto, to allow multiple bootable rpools to coexist on the
	# same system.
	$ZFS create -p $vs_pkg_repo
	check_failure $? "Unable to create $vs_pkg_repo" $SMF_FMRI exit

	for fs in $vs_pkg $vs_pkg_repo; do
		$ZFS set canmount=noauto $fs
		check_failure $? \
		    "Unable to set canmount=noauto for $fs" $SMF_FMRI exit
	done

	$ZFS allow pkg5srv create,mount,canmount,snapshot $vs_pkg_repo
	check_failure $? "Unable to delegate ZFS permissions on $vs_pkg_repo" \
	    $SMF_FMRI exit

	$CHOWN pkg5srv:pkg5srv $vs_pkg_path
	check_failure $? "Unable to chown $vs_pkg_path" $SMF_FMRI exit
	;;
esac

exit $SMF_EXIT_OK
