'\" te
.\" Copyright (c) 2007, 2011, Oracle and/or its affiliates. All rights reserved.
.TH pkgmerge 1 "2011 年 7 月 28 日" "SunOS 5.11" "ユーザーコマンド"
.SH 名前
pkgmerge \- Image Packaging System パッケージマージユーティリティー
.SH 形式
.LP
.nf
/usr/bin/pkgmerge [-n] -d \fIdest_repo\fR
    -s \fIvariant\fR=\fIvalue\fR[,...],\fIsrc_repo\fR ...
    [\fIpkg_fmri_pattern\fR ...]
.fi

.SH 機能説明
.sp
.LP
\fBpkgmerge\fR は、複数バリアントのパッケージを作成するためのパッケージ公開ツールです。このツールはそのために、名前とバージョン (タイムスタンプは除外) が同じパッケージをマージし、特定のソースの指定されたバリアント名および値とマージされるバージョン内で一意であるアクションをタグ付けしたあと、新しいパッケージをターゲットリポジトリに公開します。各ソースのすべてのパッケージの最新バージョンのみが使用されます。
.sp
.LP
アクションの属性 \fBpkg.merge.blend\fR がマージされるバリアントの名前に設定されている場合は、アクションの最終的な出力に追加されたバリアントタグが含まれないようにするために、そのアクションはマージの前にほかのマニフェストにコピーされます。属性 \fBpkg.merge.blend\fR 自体は、出力マニフェストですべてのアクションから削除されることに注意してください。この属性は、複数のパスマージに異なる値を使用して繰り返すことができます。
.sp
.LP
入力マニフェスト内の同じパスに入る同一でないアクションがあると、\fBpkgmerge\fR はエラーで終了します。
.SH オプション
.sp
.LP
次のオプションがサポートされています。
.sp
.ne 2
.mk
.na
\fB\fB-d\fR \fIdest_repo\fR\fR
.ad
.sp .6
.RS 4n
マージされたパッケージを公開する先のターゲットリポジトリのファイルシステムのパスまたは URI。このターゲットリポジトリはすでに存在している必要があります。新しいリポジトリは、\fBpkgrepo\fR(1) を使用して作成できます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-n\fR\fR
.ad
.sp .6
.RS 4n
ターゲットリポジトリを変更することなく、試験実行を行います。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-s\fR \fIvariant\fR=\fI value\fR[,...],\fIsrc_repo\fR\fR
.ad
.sp .6
.RS 4n
このソースのパッケージに使用するバリアント名および値。そのあとに、パッケージを取得する元のソースリポジトリまたはパッケージアーカイブのファイルシステムのパスまたは URI が続きます。複数のバリアントをコンマで区切って指定できます。すべてのソースに対して同じバリアントを指定する必要があります。このオプションは複数回指定できます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB--help\fR or \fB-?\fR\fR
.ad
.sp .6
.RS 4n
使用方法に関するメッセージを表示します。
.RE

.SH 環境
.sp
.LP
次の環境変数がサポートされています。
.sp
.ne 2
.mk
.na
\fB\fBTMPDIR\fR\fR
.ad
.RS 10n
.rt  
プログラム実行中に一時データが格納されるディレクトリの絶対パス。設定されていない場合、一時データはデフォルトで \fB/var/tmp\fR に格納されます。
.RE

.SH 使用例
.LP
\fB例 1 \fRバリアント名および値を指定する
.sp
.LP
指定されたソース内に見つかった各パッケージを、取得元のソースに指定された特定のバリアント名および値でタグ付けします。

.sp
.in +2
.nf
$ \fBpkgmerge -s arch=sparc,http://src.example.com \e\fR
\fB-d http://dest.example.com\fR
.fi
.in -2
.sp

.sp
.LP
サンプルパッケージ:

.sp
.in +2
.nf
set name=pkg.fmri value=pkg://example.com/foo@5.11,5.11-0.200:20381001T163427Z
dir group=sys mode=0755 owner=root path=usr
.fi
.in -2

.sp
.LP
操作のあとのサンプルパッケージ:

.sp
.in +2
.nf
set name=pkg.fmri value=pkg://example.com/foo@5.11,5.11-0.200:20381001T163427Z
set name=variant.arch value=sparc
dir group=sys mode=0755 owner=root path=usr
.fi
.in -2

.LP
\fB例 2 \fRパッケージをマージおよび公開する
.sp
.LP
特定のソースの最新バージョンの各パッケージをマージし、新しいパッケージをターゲットリポジトリに公開します。

.sp
.in +2
.nf
$ \fBpkgmerge -s arch=sparc,http://src1.example.com \e\fR
\fB-s arch=i386,http://src2.example.com \e\fR
\fB-d /\fIpath/to/target/repository\fR\fR
.fi
.in -2
.sp

.sp
.LP
ソース 1 (SPARC) のサンプルパッケージ:

.sp
.in +2
.nf
set name=pkg.fmri value=pkg://example.com/foo@5.11,5.11-0.200:20381001T121410Z
file \fIid\fR mode=0555 owner=root group=bin path=usr/bin/foo
dir group=sys mode=0755 owner=root path=usr
.fi
.in -2

.sp
.LP
ソース 2 (i386) のサンプルパッケージ:

.sp
.in +2
.nf
set name=pkg.fmri value=pkg://example.com/foo@5.11,5.11-0.200:20381001T163427Z
file \fIid\fR mode=0555 owner=root group=bin path=usr/bin/foo
dir group=sys mode=0755 owner=root path=usr
.fi
.in -2

.sp
.LP
マージされたパッケージ:

.sp
.in +2
.nf
set name=pkg.fmri value=pkg://example.com/foo@5.11,5.11-0.200:20381001T163427Z
set name=variant.arch value=sparc value=i386
file \fIid\fR mode=0555 owner=root group=bin path=usr/bin/foo variant.arch=sparc
file \fIid\fR mode=0555 owner=root group=bin path=usr/bin/foo variant.arch=i386
dir group=sys mode=0755 owner=root path=usr
.fi
.in -2

.LP
\fB例 3 \fRi386 システムと SPARC システムのデバッグおよびデバッグ以外のパッケージをマージする
.sp
.LP
i386 システムと SPARC システムの一連のデバッグおよびデバッグ以外のリポジトリ内の最新バージョンの各パッケージをマージします。

.sp
.in +2
.nf
$ \fBpkgmerge -s arch=sparc,debug=false,/repo/sparc-nondebug \e\fR
\fB-s arch=sparc,debug=true,/repo/sparc-debug \e\fR
\fB-s arch=i386,debug=false,/repo/i386-nondebug \e\fR
\fB-s arch=i386,debug=true,/repo/i386-debug \e\fR
\fB-d /\fIpath/to/target/repository\fR\fR
.fi
.in -2
.sp

.sp
.LP
ソース 1 (SPARC デバッグ以外) のサンプルパッケージ:

.sp
.in +2
.nf
set name=pkg.fmri value=pkg://example.com/foo@5.11,5.11-0.200:20381001T121410Z
file \fIid\fR mode=0555 owner=root group=bin path=usr/bin/foo
dir group=sys mode=0755 owner=root path=usr
.fi
.in -2

.sp
.LP
ソース 2 (SPARC デバッグ) のサンプルパッケージ:

.sp
.in +2
.nf
set name=pkg.fmri value=pkg://example.com/foo@5.11,5.11-0.200:20381001T121411Z
file \fIid\fR mode=0555 owner=root group=bin path=usr/bin/foo
dir group=sys mode=0755 owner=root path=usr
.fi
.in -2

.sp
.LP
ソース 3 (i386 デバッグ以外) のサンプルパッケージ:

.sp
.in +2
.nf
set name=pkg.fmri value=pkg://example.com/foo@5.11,5.11-0.200:20381001T163427Z
file \fIid\fR mode=0555 owner=root group=bin path=usr/bin/foo
dir group=sys mode=0755 owner=root path=usr
.fi
.in -2

.sp
.LP
ソース 4 (i386 デバッグ) のサンプルパッケージ:

.sp
.in +2
.nf
set name=pkg.fmri value=pkg://example.com/foo@5.11,5.11-0.200:20381001T163428Z
file \fIid\fR mode=0555 owner=root group=bin path=usr/bin/foo
dir group=sys mode=0755 owner=root path=usr
.fi
.in -2

.sp
.LP
マージされたパッケージ:

.sp
.in +2
.nf
set name=pkg.fmri value=pkg://example.com/foo@5.11,5.11-0.200:20381001T163428Z
set name=variant.arch value=sparc value=i386
set name=variant.debug value=false value=true
file \fIid\fR mode=0555 owner=root group=bin path=usr/bin/foo variant.arch=sparc variant.debug=false
file \fIid\fR mode=0555 owner=root group=bin path=usr/bin/foo variant.arch=sparc variant.debug=true
file \fIid\fR mode=0555 owner=root group=bin path=usr/bin/foo variant.arch=i386 variant.debug=false
file \fIid\fR mode=0555 owner=root group=bin path=usr/bin/foo variant.arch=i386 variant.debug=true
dir group=sys mode=0755 owner=root path=usr
.fi
.in -2

.LP
\fB例 4 \fR\fBpkg.merge.blend\fR を使用してマージする
.sp
.LP
\fBpkg.merge.blend\fR 属性を使用して、競合しない 2 つのアーキテクチャーのパッケージをマージします。

.sp
.in +2
.nf
$ \fBpkgmerge -s arch=sparc,http://src1/example.com \e\fR
\fB-s arch=i386,http://src2.example.com \e\fR
\fB-d /\fIpath/to/target/repository\fR\fR
.fi
.in -2
.sp

.sp
.LP
ソース 1 (SPARC) のサンプルパッケージ:

.sp
.in +2
.nf
set name=pkg.fmri value=pkg://example.com/foo@5.11,5.11-0.200:20381001T121410Z
file 1d5eac1aab628317f9c088d21e4afda9c754bb76 mode=0555 owner=root \e
    group=bin path=usr/bin/sparc/foo pkg.merge.blend=arch
file d285ada5f3cae14ea00e97a8d99bd3e357caadc0 mode=0555 owner=root \e
    group=bin path=usr/bin/foo
dir group=sys mode=0755 owner=root path=usr
.fi
.in -2

.sp
.LP
ソース 2 (i386) のサンプルパッケージ:

.sp
.in +2
.nf
set name=pkg.fmri value=pkg://example.com/foo@5.11,5.11-0.200:20381001T163427Z
file a285ada5f3cae14ea00e97a8d99bd3e357cb0dca mode=0555 owner=root \e
    group=bin path=usr/bin/i386/foo pkg.merge.blend=arch
file d285ada5f3cae14ea00e97a8d99bd3e357caadc0 mode=0555 owner=root \e
    group=bin path=usr/bin/foo
dir group=sys mode=0755 owner=root path=usr
.fi
.in -2

.sp
.LP
マージされたパッケージ:

.sp
.in +2
.nf
set name=pkg.fmri value=pkg://example.com/foo@5.11,5.11-0.200:20381001T163427Z
set name=variant.arch value=sparc value=i386
file d285ada5f3cae14ea00e97a8d99bd3e357caadc0 mode=0555 owner=root \e
    group=bin path=usr/bin/foo
file a285ada5f3cae14ea00e97a8d99bd3e357cb0dca mode=0555 owner=root \e
    group=bin path=usr/bin/i386/foo
file 1d5eac1aab628317f9c088d21e4afda9c754bb76 mode=0555 owner=root \e
    group=bin path=usr/bin/sparc/foo
dir group=sys mode=0755 owner=root path=usr
.fi
.in -2

.SH 終了ステータス
.sp
.LP
次の終了値が返されます。
.sp
.ne 2
.mk
.na
\fB\fB0\fR\fR
.ad
.RS 6n
.rt  
コマンドが成功しました。
.RE

.sp
.ne 2
.mk
.na
\fB\fB1\fR\fR
.ad
.RS 6n
.rt  
エラーが発生しました。
.RE

.sp
.ne 2
.mk
.na
\fB\fB2\fR \fR
.ad
.RS 6n
.rt  
無効なコマンド行オプションが指定されました。
.RE

.sp
.ne 2
.mk
.na
\fB\fB99\fR\fR
.ad
.RS 6n
.rt  
予期しない例外が発生しました。
.RE

.SH 属性
.sp
.LP
次の属性については、\fBattributes\fR(5) を参照してください。
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性タイプ属性値
_
使用条件\fBpackage/pkg\fR
_
インタフェースの安定性不確実
.TE

.SH 関連項目
.sp
.LP
\fBpkgrepo\fR(1), \fBpkg\fR(5)
.sp
.LP
\fBhttp://hub.opensolaris.org/bin/view/Project+pkg/\fR
