'\" te
.\" Copyright (c) 2007, 2012, Oracle and/or its affiliates. All rights reserved.
.TH pkgrecv 1 "12 Oct 2012" "SunOS 5.12" "User Commands"
.SH NAME
pkgrecv \- Image Packaging System content retrieval utility
.SH SYNOPSIS
.LP
.nf
/usr/bin/pkgrecv [-s \fIsrc_uri\fR] [-a] [-d (\fIpath\fR|\fIdest_uri\fR)]
    [-c \fIcache_dir\fR] [-kr] [-m \fImatch\fR] [-n] [--raw]
    [--key \fIkeyfile\fR --cert \fIcertfile\fR] (\fIfmri\fR|\fIpattern\fR) ...
.fi

.LP
.nf
/usr/bin/pkgrecv [-s \fIsrc_uri\fR] --newest
.fi

.SH DESCRIPTION
.sp
.LP
\fBpkgrecv\fR retrieves packages from a \fBpkg\fR(5) repository or package archive and republishes the retrieved packages to a different package repository or package archive. By default, packages are retrieved in package repository format suitable for use with \fBpkg\fR, \fBpkg.depotd\fR, and package publication tools.
.LP
Note - 
.sp
.RS 2
Do not use multiple instances of \fBpkgrecv\fR simultaneously to republish packages to the same destination repository or archive. In this case, newly received packages could contain duplicate actions.
.RE
.sp
.LP
After a \fBpkgrecv\fR operation that retrieves packages into a \fIdest_uri\fR, if the \fIdest_uri\fR repository must support \fBpkg search\fR operations, run \fBpkgrepo refresh\fR on that repository to update search indexes.
.SH OPTIONS
.sp
.LP
The following options are supported:
.sp
.ne 2
.mk
.na
\fB\fB-h\fR\fR
.ad
.sp .6
.RS 4n
Display a usage message.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-a\fR\fR
.ad
.sp .6
.RS 4n
Store the retrieved package data in a \fBpkg\fR(5) archive at the location specified by \fB-d\fR. The file cannot already exist. This option can be used only with file system based destinations. Although not required, using a file extension of \fB\&.p5p\fR (for example, \fBarchive.p5p\fR) is strongly suggested. This option cannot be combined with \fB--raw\fR.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-c\fR \fIcache_dir\fR\fR
.ad
.sp .6
.RS 4n
Specify the path to a directory that will be used to cache downloaded content. If this directory is not supplied, the client automatically selects a cache directory. In the case where a download is interrupted, and a cache directory was automatically chosen, use this option to resume the download. See the "Environment Variables" section below for details about how to set the location used for temporary data storage.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-d\fR (\fIpath\fR|\fIdest_uri\fR)\fR
.ad
.sp .6
.RS 4n
Specify the file system path or URI of the target to republish packages to. If \fB-a\fR  is specified, the target is a new package archive that cannot already exist. Otherwise, the target must be a package repository that already exists. New repositories can be created using the \fBpkgrepo\fR command. If \fB-d\fR is not specified, the value of \fBPKG_DEST\fR is used. See "Environment Variables" below.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-k\fR\fR
.ad
.sp .6
.RS 4n
Keep the retrieved package content compressed. This option is ignored when republishing. Compressed package content should not be used with \fBpkgsend\fR.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-m\fR \fImatch\fR\fR
.ad
.sp .6
.RS 4n
Control matching behavior using the following values:
.sp
.ne 2
.mk
.na
\fB\fBall-timestamps\fR\fR
.ad
.sp .6
.RS 4n
Includes all matching timestamps, not just the latest (implies \fBall-versions\fR).
.RE

.sp
.ne 2
.mk
.na
\fB\fBall-versions\fR\fR
.ad
.sp .6
.RS 4n
Includes all matching versions, not just the latest.
.RE

.RE

.sp
.ne 2
.mk
.na
\fB\fB-n\fR\fR
.ad
.sp .6
.RS 4n
Perform a trial run with no changes made.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-r\fR\fR
.ad
.sp .6
.RS 4n
Recursively retrieve all dependencies for the provided list of packages.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-s\fR \fIsrc_uri\fR\fR
.ad
.sp .6
.RS 4n
Specify a URI representing the location of a \fBpkg\fR(5) repository or package archive from which to receive package data. If \fB-s\fR is not specified, the value of \fBPKG_SRC\fR is used. See "Environment Variables" below.
.RE

.sp
.ne 2
.mk
.na
\fB\fB--cert\fR \fIcertfile\fR\fR
.ad
.sp .6
.RS 4n
Specify a client SSL certificate file to use for package retrieval from an HTTPS repository.
.RE

.sp
.ne 2
.mk
.na
\fB\fB--key\fR \fIkeyfile\fR\fR
.ad
.sp .6
.RS 4n
Specify a client SSL key file to use for package retrieval from an HTTPS repository.
.RE

.sp
.ne 2
.mk
.na
\fB\fB--newest\fR\fR
.ad
.sp .6
.RS 4n
List the most recent versions of the packages available from the specified repository and exit. All other options except \fB-s\fR are ignored.
.RE

.sp
.ne 2
.mk
.na
\fB\fB--raw\fR\fR
.ad
.sp .6
.RS 4n
Retrieve and store the raw package data in a set of directory structures by stem and version at the location specified by \fB-d\fR. This option can be used only with file system based destinations. This package data can be used to conveniently modify and republish packages, perhaps by correcting file contents or providing additional package metadata. This option cannot be combined with \fB-a\fR.
.RE

.SH OPERANDS
.sp
.ne 2
.mk
.na
\fB\fB\fIfmri\fR|\fIpattern\fR\fR\fR
.ad
.sp .6
.RS 4n
If \fB\&'*'\fR is specified for \fIpattern\fR, and if the \fB-d\fR argument does not contain any packages published by \fIsrc_uri\fR publishers, the newest versions of all packages in the \fIsrc_uri\fR, and any other dependencies of those packages, are retrieved.
.sp
If \fB\&'*'\fR is specified for \fIpattern\fR, and if the \fB-d\fR argument already contains packages published by one or more \fIsrc_uri\fR publishers, only new and changed packages from those publishers in the \fIsrc_uri\fR are retrieved.
.sp
If \fB\fIfmri\fR|\fIpattern\fR\fR is not \fB\&'*'\fR, then the specified packages are retrieved. You might want to specify the \fB-r\fR option to be sure to retrieve all the dependencies of the specified packages.
.RE

.SH EXAMPLES
.LP
\fBExample 1 \fRList Newest Packages
.sp
.LP
List the newest packages available from the repository on the system named \fBtest\fR.

.sp
.in +2
.nf
$ \fBpkgrecv -s http://test --newest\fR
pkg://solaris/system/library/c++-runtime@0.5.11,5.11-0.175.0.0.0.2.1:20120921T190358Z
pkg://solaris/system/library/freetype-2@2.4.8,5.11-0.175.1.0.0.7.1234:20120109T215840Z
pkg://solaris/system/library/math@0.5.11,5.11-0.175.0.0.0.2.1:20120921T190432Z
.fi
.in -2
.sp

.LP
\fBExample 2 \fRRetrieve Raw Package Data
.sp
.LP
Receive the \fBc++-runtime\fR package from Example 1 in a format suitable for use with \fBpkgsend publish\fR.

.sp
.in +2
.nf
$ \fBpkgrecv -s http://test \e\fR
\fB-d /local/repo --raw \e\fR
\fBc++-runtime@0.5.11,5.11-0.175.0.0.0.2.1:20120921T190358Z\fR
Processing packages for publisher solaris ...
Retrieving and evaluating 1 package(s)...
PROCESS       ITEMS     GET (MB)    SEND (MB)
Completed       1/1      3.5/3.5      0.0/0.0
$ \fBls /local/repo\fR
pkg5.repository  publisher  system%2Flibrary%2Fc%2B%2B-runtime
.fi
.in -2
.sp

.LP
\fBExample 3 \fRRetrieve Dependencies From a System
.sp
.LP
Receive the package \fBeditor/vim\fR and all of its dependencies from the system named \fBtest\fR.

.sp
.in +2
.nf
$ \fBpkgrecv -s http://test -d /local/repo -r editor/vim\fR
.fi
.in -2
.sp

.LP
\fBExample 4 \fRRetrieve All Versions
.sp
.LP
Receive all versions of the package \fBeditor/vim\fR from the system named \fBtest\fR.

.sp
.in +2
.nf
$ \fBpkgrecv -s http://test -d /local/repo -m all-versions \e\fR
\fBeditor/vim\fR
Processing packages for publisher solaris ...
Retrieving and evaluating 2 package(s)...
PROCESS       ITEMS     GET (MB)    SEND(MB)
Completed       2/2    16.7/16.7    44.9/44.9
.fi
.in -2
.sp

.LP
\fBExample 5 \fRRetrieve All Versions and Republish Remotely
.sp
.LP
Receive all versions of the package \fBlibrary/zlib\fR from the system named \fBtest\fR and republish it to a remote repository on the system named \fBremote\fR.

.sp
.in +2
.nf
$ \fBpkgrecv -s http://test -d http://remote:10000 \e\fR
\fB-m all-versions library/zlib\fR
.fi
.in -2
.sp

.LP
\fBExample 6 \fRRetrieve Dependencies From a Repository
.sp
.LP
Receive the package \fBeditor/gnu-emacs\fR and all of its dependencies from the repository located at \fB/export/repo\fR.

.sp
.in +2
.nf
$ \fBpkgrecv -s /export/repo -d /local/repo -r editor/gnu-emacs\fR
.fi
.in -2
.sp

.LP
\fBExample 7 \fRRetrieve Additional Packages and Changed Content
.sp
.LP
Receive all packages that do not already exist and all changed content from the repository located at \fBhttp://pkg.oracle.com/solaris/release/\fR to the repository located at \fB/export/repoSolaris11\fR.

.sp
.in +2
.nf
$ \fBpkgrecv -s http://pkg.oracle.com/solaris/release/ \e\fR
\fB-d /export/repoSolaris11 -m all-timestamps '*'\fR
.fi
.in -2
.sp

.sp
.LP
Receive all packages that do not already exist and all changed content from the secure repository located at \fBhttp://pkg.oracle.com/solaris/support/\fR to the repository located at \fB/export/repoSolaris11\fR.

.sp
.in +2
.nf
$ \fBpkgrecv -s http://pkg.oracle.com/solaris/support/ \e\fR
\fB-d /export/repoSolaris11 -m all-timestamps \e\fR
\fB--key /var/pkg/ssl/Oracle_Solaris_11_Support.key.pem \e\fR
\fB--cert /var/pkg/ssl/Oracle_Solaris_11_Support.certificate.pem '*'\fR
.fi
.in -2
.sp

.LP
\fBExample 8 \fRCreate a Package Archive
.sp
.LP
Create a package archive containing the package \fBeditor/gnu-emacs\fR and all of its dependencies from the repository located at \fBhttp://example.com:10000\fR.

.sp
.in +2
.nf
$ \fBpkgrecv -s http://example.com:10000 -d /my/emacs.p5p -a \e\fR
\fB-r editor/gnu-emacs\fR
.fi
.in -2
.sp

.LP
\fBExample 9 \fRCopy Packages From an Archive to a Repository
.sp
.LP
Copy all of the packages in a package archive to an existing repository located at \fB/export/repo\fR.

.sp
.in +2
.nf
$ \fBpkgrecv -s /my/archive.p5p -d /export/repo '*'\fR
.fi
.in -2
.sp

.SH ENVIRONMENT VARIABLES
.sp
.LP
The following environment variables are supported:
.sp
.ne 2
.mk
.na
\fB\fBPKG_DEST\fR\fR
.ad
.RS 12n
.rt  
The path of a directory to save the retrieved package to, or the file system path or URI of a repository or package archive where the packages will be copied.
.RE

.sp
.ne 2
.mk
.na
\fB\fBPKG_SRC\fR\fR
.ad
.RS 12n
.rt  
A URI or file system path representing the location of a \fBpkg\fR(5) repository or package archive from which to retrieve packages.
.RE

.sp
.ne 2
.mk
.na
\fB\fBTMPDIR\fR\fR
.ad
.RS 12n
.rt  
The absolute path of the directory where temporary data should be stored during program execution. If not set, the default is to store temporary data in \fB/var/tmp\fR.
.RE

.SH EXIT STATUS
.sp
.LP
The following exit values are returned:
.sp
.ne 2
.mk
.na
\fB\fB0\fR\fR
.ad
.RS 6n
.rt  
Command succeeded.
.RE

.sp
.ne 2
.mk
.na
\fB\fB1\fR\fR
.ad
.RS 6n
.rt  
An error occurred.
.RE

.sp
.ne 2
.mk
.na
\fB\fB2\fR\fR
.ad
.RS 6n
.rt  
Invalid command line options were specified.
.RE

.sp
.ne 2
.mk
.na
\fB\fB3\fR\fR
.ad
.RS 6n
.rt  
Multiple operations were requested, but only some of them succeeded.
.RE

.sp
.ne 2
.mk
.na
\fB\fB99\fR\fR
.ad
.RS 6n
.rt  
An unanticipated exception occurred.
.RE

.SH ATTRIBUTES
.sp
.LP
See \fBattributes\fR(5) for descriptions of the following attributes:
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
Availability\fBpackage/pkg\fR
_
Interface StabilityUncommitted
.TE

.SH SEE ALSO
.sp
.LP
\fBpkgrepo\fR(1), \fBpkgsend\fR(1), \fBpkg\fR(5)
.sp
.LP
\fICopying and Creating Oracle Solaris 11.1 Package Repositories\fR
.sp
.LP
\fBhttp://hub.opensolaris.org/bin/view/Project+pkg/\fR
