#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Configure Xvnc if we're in a PV domU.  We write the password out to the
# dom0 via xenstore, on the presumption that anyone who can read
# xenstore also has permission to reach this domain during the install.
# We also provide a simple way to enable this post-install for those
# users who are happy doing so.
#

. /lib/svc/share/smf_include.sh

case $1 in
"start")
	;;
*)
	exit $SMF_EXIT_ERR_FATAL
	;;
esac

X11FMRI="svc:/application/x11/x11-server"
PASSWDFILE="/etc/X11/.vncpasswd"
PORT=5900

check_is_domu()
{
	if [ `uname -p` != "i386" -o `uname -i` != "i86xpv" ]; then
		exit $SMF_EXIT_OK
	fi

        /usr/sbin/devfsadm -i domcaps
        domcaps=`cat /dev/xen/domcaps 2>/dev/null`
        echo "$domcaps" | grep "control_d" > /dev/null
	if [ $? = 0 ]; then
		exit $SMF_EXIT_OK
	fi
}

enable()
{
	PASSWD=`/usr/bin/openssl rand -base64 8 2>/dev/null | cut -c0-8`
	printf "%s\n%s\n" "$PASSWD" "$PASSWD" | \
	    /usr/bin/vncpasswd $PASSWDFILE >/dev/null

	/usr/sbin/svccfg -s $X11FMRI setprop options/server = astring: \
	    "/usr/X11/bin/Xvnc"
	echo "setprop options/server_args = astring: " \
	    "\"-rfbauth=$PASSWDFILE\"" | /usr/sbin/svccfg -s $X11FMRI

	/usr/lib/xen/bin/xenstore-write guest/vnc/passwd $PASSWD
	/usr/lib/xen/bin/xenstore-write guest/vnc/port $PORT
}

disable()
{
	SERVER=`/usr/bin/svcprop -p options/server $X11FMRI 2>/dev/null`
	if [ "$SERVER" = "/usr/X11/bin/Xvnc" ]; then
		/usr/sbin/svccfg -s $X11FMRI setprop options/server = \
		    astring: "/usr/X11/bin/Xorg"
		/usr/sbin/svccfg -s $X11FMRI setprop options/server_args = \
		    astring: ""
	fi
}

check_is_domu

XVMVNC=`/usr/bin/svcprop -p options/xvm_vnc $X11FMRI 2>/dev/null`
if [ -z "$XVMVNC" ]; then
	if [ -f /.livecd ]; then
		XVMVNC="true"
	else
		XVMVNC="false"
		/usr/sbin/svccfg -s $X11FMRI setprop options/xvm_vnc = \
		    astring: $XVMVNC
		disable
	fi
fi

if [ "$XVMVNC" = "true" ]; then
	enable
fi

exit $SMF_EXIT_OK
